In [1]:
import pandas as pd
import gzip

In [3]:
def parse(path):
  g = gzip.open(path, 'rb')
  for l in g:
    yield eval(l)

In [4]:
def getDF(path):
  i = 0
  df = {}
  for d in parse(path):
    df[i] = d
    i += 1
  return pd.DataFrame.from_dict(df, orient='index')

In [5]:
df = getDF('reviews_Grocery_and_Gourmet_Food_5.json.gz')

In [6]:
df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A1VEELTKS8NLZB,616719923X,Amazon Customer,"[0, 0]",Just another flavor of Kit Kat but the taste i...,4.0,Good Taste,1370044800,"06 1, 2013"
1,A14R9XMZVJ6INB,616719923X,amf0001,"[0, 1]",I bought this on impulse and it comes from Jap...,3.0,"3.5 stars, sadly not as wonderful as I had hoped",1400457600,"05 19, 2014"
2,A27IQHDZFQFNGG,616719923X,Caitlin,"[3, 4]",Really good. Great gift for any fan of green t...,4.0,Yum!,1381190400,"10 8, 2013"
3,A31QY5TASILE89,616719923X,DebraDownSth,"[0, 0]","I had never had it before, was curious to see ...",5.0,Unexpected flavor meld,1369008000,"05 20, 2013"
4,A2LWK003FFMCI5,616719923X,Diana X.,"[1, 2]",I've been looking forward to trying these afte...,4.0,"Not a very strong tea flavor, but still yummy ...",1369526400,"05 26, 2013"

In [20]:
df_small = df[:100000]
df_small

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A1VEELTKS8NLZB,616719923X,Amazon Customer,"[0, 0]",Just another flavor of Kit Kat but the taste i...,4.0,Good Taste,1370044800,"06 1, 2013"
1,A14R9XMZVJ6INB,616719923X,amf0001,"[0, 1]",I bought this on impulse and it comes from Jap...,3.0,"3.5 stars, sadly not as wonderful as I had hoped",1400457600,"05 19, 2014"
2,A27IQHDZFQFNGG,616719923X,Caitlin,"[3, 4]",Really good. Great gift for any fan of green t...,4.0,Yum!,1381190400,"10 8, 2013"
3,A31QY5TASILE89,616719923X,DebraDownSth,"[0, 0]","I had never had it before, was curious to see ...",5.0,Unexpected flavor meld,1369008000,"05 20, 2013"
4,A2LWK003FFMCI5,616719923X,Diana X.,"[1, 2]",I've been looking forward to trying these afte...,4.0,"Not a very strong tea flavor, but still yummy ...",1369526400,"05 26, 2013"
...,...,...,...,...,...,...,...,...,...
99995,AQZ4PHIEEV5N5,B004JGQ15E,"Penny Pinching Polly ""Check out my website fo...","[0, 0]",My 5 year old and I love these! While it's tr...,5.0,Delicious Sweet & Salty Treat!,1305590400,"05 17, 2011"
99996,A37D2TGTIXRV2N,B004JGQ15E,"plyopowerd ""Arrow Dynamic Mom""","[0, 0]",It's exactly what is pictured on the box (how ...,5.0,Delicious and well packaged,1304726400,"05 7, 2011"
99997,AQ2FC1DLKVD8H,B004JGQ15E,P. McWhorter,"[1, 1]","To me, I did not enjoy these that much, and wo...",2.0,Not so Great,1304380800,"05 3, 2011"
99998,A2JZ8T64YZDQSI,B004JGQ15E,"~purplemoon~ ""The Quiet Corner""","[0, 0]","Which, of course, if you REALLY like EXTREMELY...",3.0,*Extremely* sweet!,1303862400,"04 27, 2011"
99999,AVL5IDEE8YA3D,B004JGQ15E,Rachel McElhany,"[0, 0]",I love sweet and salty food combinations - usu...,4.0,Good sweet and salty combo,1303776000,"04 26, 2011"

In [21]:
 df_review = df_small[["reviewText", "overall"]]
df_review

                                              reviewText  overall
0      Just another flavor of Kit Kat but the taste i...      4.0
1      I bought this on impulse and it comes from Jap...      3.0
2      Really good. Great gift for any fan of green t...      4.0
3      I had never had it before, was curious to see ...      5.0
4      I've been looking forward to trying these afte...      4.0
...                                                  ...      ...
99995  My 5 year old and I love these!  While it's tr...      5.0
99996  It's exactly what is pictured on the box (how ...      5.0
99997  To me, I did not enjoy these that much, and wo...      2.0
99998  Which, of course, if you REALLY like EXTREMELY...      3.0
99999  I love sweet and salty food combinations - usu...      4.0

[100000 rows x 2 columns]

In [22]:
df_classify = df_review.loc[df_review["overall"] < 5 ]
df_classify

                                              reviewText  overall
0      Just another flavor of Kit Kat but the taste i...      4.0
1      I bought this on impulse and it comes from Jap...      3.0
2      Really good. Great gift for any fan of green t...      4.0
4      I've been looking forward to trying these afte...      4.0
5      These Kit-kats are very good, but if you're lo...      4.0
...                                                  ...      ...
99992  Snackwell Fudge Drizzle Caramel Popcorn is sur...      4.0
99994  First of all, this is not health food.  It's m...      4.0
99997  To me, I did not enjoy these that much, and wo...      2.0
99998  Which, of course, if you REALLY like EXTREMELY...      3.0
99999  I love sweet and salty food combinations - usu...      4.0

[38018 rows x 2 columns]

In [30]:
df_classify["reviewText"][5]

"These Kit-kats are very good, but if you're looking for a strong green tea flavor- you will be disappointed. The green tea flavor is very subtle."

In [23]:
df_classify.count()

reviewText    38018
overall       38018
dtype: int64

In [24]:
df_classify["reviewText"][986]

'Normal Sea Salt. I have about 17 salts and this is one of my normal Sea Salts. Nothing fancy about it.'

In [25]:
df_review.loc[df_review["overall"] < 5, "overall"] = 0
df_review

C:\Users\Babette\anaconda3\envs\PythonAdv\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

                                              reviewText  overall
0      Just another flavor of Kit Kat but the taste i...      0.0
1      I bought this on impulse and it comes from Jap...      0.0
2      Really good. Great gift for any fan of green t...      0.0
3      I had never had it before, was curious to see ...      5.0
4      I've been looking forward to trying these afte...      0.0
...                                                  ...      ...
99995  My 5 year old and I love these!  While it's tr...      5.0
99996  It's exactly what is pictured on the box (how ...      5.0
99997  To me, I did not enjoy these that much, and wo...      0.0
99998  Which, of course, if you REALLY like EXTREMELY...      0.0
99999  I love sweet and salty food combinations - usu...      0.0

[100000 rows x 2 columns]

In [26]:
df_review.loc[df_review["overall"] == 5, "overall"] = 1
df_review

C:\Users\Babette\anaconda3\envs\PythonAdv\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

                                              reviewText  overall
0      Just another flavor of Kit Kat but the taste i...      0.0
1      I bought this on impulse and it comes from Jap...      0.0
2      Really good. Great gift for any fan of green t...      0.0
3      I had never had it before, was curious to see ...      1.0
4      I've been looking forward to trying these afte...      0.0
...                                                  ...      ...
99995  My 5 year old and I love these!  While it's tr...      1.0
99996  It's exactly what is pictured on the box (how ...      1.0
99997  To me, I did not enjoy these that much, and wo...      0.0
99998  Which, of course, if you REALLY like EXTREMELY...      0.0
99999  I love sweet and salty food combinations - usu...      0.0

[100000 rows x 2 columns]

In [27]:
#Saving sample file to csv
df_review.to_csv('sample.csv')